#!/bin/bash

# $1 is directory name
[ "$1" == "" ] && echo "Usage: $0 [PATHNAME] to clear away the blanks..." && exit 0

find "$1" -type f -name "* *" | while read name
do
    na=$(echo "$name" | sed 's/\ //g')
    mv -v "$name" "$na"
done

find "$1" -type f -name "*（*" | while read name
do
    na=$(echo "$name" | sed 's/（/(/g')
    mv -v "$name" "$na"
done

find "$1" -type f -name "*）*" | while read name
do
    na=$(echo "$name" | sed 's/）/)/g')
    mv -v "$name" "$na"
done

# Replace
find "$1" -type f -name "*(*" | while read name
do
    na=$(echo "$name" | sed 's/(/_/g')
    mv -v "$name" "$na"
done
find "$1" -type f -name "*)*" | while read name
do
    na=$(echo "$name" | sed 's/)/_/g')
    mv -v "$name" "$na"
done
find "$1" -type f -name "*&*" | while read name
do
    na=$(echo "$name" | sed 's/&/_/g')
    mv -v "$name" "$na"
done

